#!/usr/bin/env python
# -*- encoding: utf8 -*-

'''
Change _gen_command if you don't use vim.
Change input mappings if you are not used to the default inputs.
'''

import sys
import optparse
import os

import gj_util


__author__ = 'fcamel'


#------------------------------------------------------------------------------
# Configuration
#------------------------------------------------------------------------------
def _gen_vim_command(filename, line, pattern):
    return 'vi %s -c/%s +%s' % (filename, pattern, line)

_gen_command = _gen_vim_command

#------------------------------------------------------------------------------
# main
#------------------------------------------------------------------------------
def main():
    '''\
    %prog [options] <pattern> [<pattern> ...]

    Grep pattern in source codes using id-utils.
    Before starting, type 'mkid' in your source root first.

    Example of usages:
        $ gj MyClient         # find any snippet which contains MyClient
        $ gj MyClient class   # find the definition.
    '''
    gj_util.check_install()

    parser = optparse.OptionParser(usage=main.__doc__)
    parser.add_option('-d', '--declaration', dest='declaration',
                      action='store_true', default=False,
                      help='Find possible declarations.')
    parser.add_option('-b', '--batch', dest='batch',
                      action='store_true', default=False,
                      help='Run in batch mode (i.e., no interaction).')
    options, args = parser.parse_args()

    if len(args) < 1:
        parser.print_help()
        sys.exit(1)

    if not os.path.exists('ID'):
        print 'Database file "ID" is not found. Have you run "mkid"?'
        return 2

    patterns = args

    # Find the initial matched set.
    gj_util.get_list.original_patterns = patterns
    if options.declaration:
        matches = gj_util.find_declaration_or_definition(patterns[0])
    else:
        matches = gj_util.get_list()

    # Run in batch mode?
    if options.batch:
        for m in matches:
            print unicode(m).encode('utf8')
        return 0

    # Enter interactive mode.
    # Filter the rest or view the selected file.
    n = 0
    while True:
        n, matches, patterns = gj_util.filter_until_select(matches, patterns, n)
        if n <= 0:
            if n < 0:
                return 1
            return 0

        # Edit the chosen one.
        m = matches[n - 1]

        ret = os.system(_gen_command(m.filename, m.line_num, patterns[0]))
        if ret != 0:
            return 2

    return 0


if __name__ == '__main__':
    sys.exit(main())
